name: Free unused disk space
description: Remove unused packages and files for Android build

runs:
  using: composite
  steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        link-to-sdk: true
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - run: |
        sudo apt-get update --fix-missing \
          && sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' '^mysql-server-core-.*' '^postgresql-.*' \
          azure-cli google-chrome-stable google-cloud-cli firefox powershell microsoft-edge-stable mono-devel \
          && sudo apt-get purge docker-ce docker-ce-cli \
          && sudo apt-get autoremove -y \
          && sudo rm -rf /usr/share/dotnet /usr/share/swift /usr/share/miniconda /usr/local/graalvm \
          /usr/local/.ghcup /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules \
          /var/lib/docker /var/lib/apt/lists
      shell: sh
