name: Android Build Test

on:
  schedule:
    # 05:00 AM (KST) Mon-Fri
    - cron: "00 20 * * 0-4"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
    - name: Set up android build
      uses: ./.github/actions/set-up
    - name: Run build
      run: ./gradlew build
    - name: Upload test reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: ml_inference_offloading/build/reports
    - name: Upload nnstreamer-api aar
      uses: actions/upload-artifact@v4
      with:
        name: nnstreamer-api-aar
        path: nnstreamer-api/build/outputs/aar/*
    - name: Upload ml_inference_offloading apk
      uses: actions/upload-artifact@v4
      with:
        name: ml-inference-offloading-apk
        path: ml_inference_offloading/build/outputs/apk/*/*.apk
