name: Android Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        link-to-sdk: true
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build
    - name: Upload nnstreamer-api aar
      uses: actions/upload-artifact@v4
      with:
        name: nnstreamer-api-aar
        path: nnstreamer-api/build/outputs/aar/*
