name: Create KDoc documentation

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up android build
      uses: ./.github/actions/set-up
    - name: Run dokka
      run: |
        ./gradlew externals:build
        ./gradlew dokkaHtml
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ml_inference_offloading/build/dokka/html
